project:
  type: website
  output-dir: docs

website:
  title: "Small RNA analysis"
  sidebar:
    style: docked
    contents:
      - text: "SmallRNA analysis"
        href: index.qmd
     
  navbar:
    right:
      - icon: github
        href: https://github.com/
        aria-label: Github
  page-footer:
    center:
      - text: "Made with love and Quarto"
        href: https://quarto.org
format:
  html:
    css: style.css
    toc: true
    